services:
  postgres:
    image: postgres:16-alpine
    container_name: midnight-technician-postgres
    environment:
      POSTGRES_DB: glabtech_db
      POSTGRES_USER: ${POSTGRES_USER:-GLABTECH_APP}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-GLABTECH_APP_PASSWORD}
    ports:
      - "5464:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo-technician
    ports:
      - "27042:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-M_T_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-M_T_PASSWORD}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [
        "CMD-SHELL",
        "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok' -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin | grep 1 >/dev/null || exit 1"
      ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  mongo_data:
  postgres_data:
    driver: local
